### PR TITLE
Add check to be usable under Windows

### PR DESCRIPTION
**Pull request by jmarcet**
Hi,

I use this module in an IPTV proxy I wrote, [movistar-u7d](https://github.com/jmarcet/movistar-u7d).

I never had an issue with it until I made my project compatible with Windows. It needs a couple minimal changes to be fully compatible. I did not touch the tests though.

Would you mind merging the PR or make the adjustments yourself, please?

Thanks in advance for your time and contributions 😄

### CODE REVIEW

**Comment by jsbronder** [comment]
Looks fine to me, but I don't use Windows so I'm not really a good judge.  A bit of googling says that AF_UNIX was a thing in WSL1 but it's gone in WSL2?

I'll leave this up for a bit just to see if anyone else comments and then merge.

**Comment by jmarcet** [comment]
I'm not talking about WSL in this case, the PR is for native Windows not for WSL. That is, to do a release of my proxy for Windows, with no WSL of any sort, I needed those changes.

All WSL use a virtual network, so for this particular case was not an option, since it added an igmp proxy of some kind to the requirements. I wanted regular people to be able to use it.

**Comment by jmarcet** [comment]
One more thing.

I've come across with a different check in the wild., `sys.platform == "win32"`, which I kind of like even better, though it is just taste I guess.

**Comment by jsbronder** [comment]
> One more thing.
> 
> I've come across with a different check in the wild., `sys.platform == "win32"`, which I kind of like even better, though it is just taste I guess.

Imitation is the highest form of flattery.  Do you mind changing the check in this PR to be the same, with a link to a couple of examples in the commit message?  I'll merge after that.

**Comment by jmarcet** [comment]
Sorry for the delay.

I've updated the PR, I've used `_windows` as name for a global variable, just like [python-ffmpeg](https://github.com/jonghwanhyeon/python-ffmpeg) does. I felt it nicer in this codebase than `WIN32` like I'm using.

I hope you like it 😄

**Comment by jsbronder** [comment]
Great, thanks!

**Pull request merged**
